Duden/Uri
DDP-Projekt/Kompilierer pull request #100
Opened 2024-11-21 08:59 UTC by bafto

Es ist oftmals nötig Uris (also auch Urls) zu parsen und zu erstellen. Dafür das (recht minimale) Duden/Uri Modul.

Es besteht aus einem Typ Uri und überlädt den "als" Operator für Text -> Uri und Uri -> Text.
Siehe den Test für mehr details.

2024-11-23 20:28 UTC, NotLe0n requested changes

2024-11-23 20:28 UTC, NotLe0n commented on lib/stdlib/Duden/Uri.ddp
> +    Speichere gruppen von t an der Stelle 9 in Fragment von ergebnis.
Du tust nicht überprüfen ob `gruppen von t` groß genug ist. Wenn zum Beispiel die Uri kein Port hat wird, gibt `gruppen von t an der Stelle 5` einen Fehler. Genau so bei den anderen.

2024-11-23 20:28 UTC, NotLe0n commented on tests/testdata/stdlib/Uri/expected.txt
Kann sein dass irgendwo ein `|` zu viel oder zu wenig ist. Konnte es nicht testen wegen dem Fehler.

2024-11-24 14:15 UTC, NotLe0n commented
Eine funktion die Queryparameter (de.: Abfragenparameter oder Abfragen) auswertet wäre noch nötig. Zum Beispiel:
```ddp
Der Text Seitenzahl ist (die Abfrage "page" von "https://example.com/book?page=8" als Uri).
```
Es sollte auch eine Funktion geben zum überprüfen ob eine bestimmte Abfrage vorhanden ist und eine Funktion die eine Liste von allen Abfragen(-schlüssel) und Abfragenwerten zurückgibt.

Eine häufig benutzte WebAPI dafür ist [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams). Von dieser kann man sich ein bisschen inspiration geben lassen.

2024-11-24 15:26 UTC, bafto commented
> Eine funktion die Queryparameter (de.: Abfragenparameter oder Abfragen) auswertet wäre noch nötig. Zum Beispiel:
> 
> ```
> Der Text Seitenzahl ist (die Abfrage "page" von "https://example.com/book?page=8" als Uri).
> ```
> 
> Es sollte auch eine Funktion geben zum überprüfen ob eine bestimmte Abfrage vorhanden ist und eine Funktion die eine Liste von allen Abfragen(-schlüssel) und Abfragenwerten zurückgibt.
> 
> Eine häufig benutzte WebAPI dafür ist [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams). Von dieser kann man sich ein bisschen inspiration geben lassen.

Ich habe es mal hinzugefügt und ein TODO dagelassen, damit wir Query parsing später zu Http Modulen o.ä. verschieben.
Die URI spec schreibt nämlich kein Format vor, das a=b&b=c Format ist reine convention.

2024-11-24 15:49 UTC, NotLe0n commented
> > Eine funktion die Queryparameter (de.: Abfragenparameter oder Abfragen) auswertet wäre noch nötig. Zum Beispiel:
> > ```
> > Der Text Seitenzahl ist (die Abfrage "page" von "https://example.com/book?page=8" als Uri).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Es sollte auch eine Funktion geben zum überprüfen ob eine bestimmte Abfrage vorhanden ist und eine Funktion die eine Liste von allen Abfragen(-schlüssel) und Abfragenwerten zurückgibt.
> > Eine häufig benutzte WebAPI dafür ist [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams). Von dieser kann man sich ein bisschen inspiration geben lassen.
> 
> Ich habe es mal hinzugefügt und ein TODO dagelassen, damit wir Query parsing später zu Http Modulen o.ä. verschieben. Die URI spec schreibt nämlich kein Format vor, das a=b&b=c Format ist reine convention.

Man könnte es noch um mehr Funktionen erweitern (siehe die WebAPI), aber ich denke es passt erstmal so.

2024-11-24 15:50 UTC, NotLe0n approved these changes

2024-11-24 15:51 UTC, merged