JSON + Compression
DDP-Projekt/Kompilierer pull request #106
Opened 2024-12-08 20:21 UTC by NotLe0n

2024-12-09 08:21 UTC, bafto requested changes

2024-12-09 08:21 UTC, bafto commented on tests/testdata/stdlib/Komprimierung/Komprimierung.ddp
> +Entpacke die Datei "expected.txt" vom Archiv "expected.zip" in den Ordner "./expected/".
Dieser Test failed noch. Ich glaube es liegt daran, dass der AusgabeOrdner parameter nicht benutzt wird, aber vielleicht benutze ich die Funktion auch falsch.

2024-12-09 08:26 UTC, bafto commented on tests/testdata/stdlib/Komprimierung/Komprimierung.ddp
> +Entpacke die Datei "expected.txt" vom Archiv "expected.zip" in den Ordner "./expected/".
Falls ich die Funktion falsch benutzt habe, bitte die Korrekte Nutzung als Kommentar zur Funktion hinzufügen

2024-12-09 17:03 UTC, bafto approved these changes

2024-12-09 17:06 UTC, bafto requested changes

2024-12-09 17:06 UTC, bafto commented on lib/stdlib/source/DDP/compression.c
> +			archive_read_free(a);
Möglicher double free? Die Parameter werden call-site auch gefreed

2024-12-09 17:06 UTC, bafto commented on lib/stdlib/source/DDP/compression.c
> +			archive_read_free(a);
Selbiges wie oben

2024-12-09 17:06 UTC, bafto commented on lib/stdlib/source/DDP/compression.c
> +			archive_read_free(a);
muss disk hier auch gefreed werden?

2024-12-09 20:25 UTC, NotLe0n commented on lib/stdlib/Duden/JSON.ddp
> +	"die Hexadezimalzahl <hex>"
Gehört das zu JSON? Diese Funktion würde meiner Meinung nach besser zu Duden/Zahlen passen.

2024-12-09 20:25 UTC, NotLe0n commented on lib/stdlib/Duden/JSON.ddp
> +	"die JsonListe <json> als Text"
Könnten die Funktionen JsonListe_zu_Text_Operator, JsonObjekt_Zu_Text_Operator und Json_Zu_Text auch nicht jeweils den als Operator überladen?

2024-12-09 20:25 UTC, NotLe0n commented on lib/stdlib/Duden/JSON.ddp
> +Binde "Duden/Ausgabe" ein.
Vergessen zu entfernen?

2024-12-10 07:32 UTC, bafto commented on lib/stdlib/Duden/JSON.ddp
> +	"die JsonListe <json> als Text"
Die Json Typen sind nur Typ-Aliase und keine Typedefs, deshalb würde das den als Operator für HashTabelle/Variable und Variablen Liste überladen.

Das Problem ist, dass ein JsonWert keine Typedef sein kann, da man den Typ Variable nicht typedefen kann (implementierungstechnisch und logisch geht das nicht). Deshalb wollte ich es einheitlich halten.

Außerdem müssten wir dann alle Funktionen einer HashTablle für das JsonObjekt neu hinzufügen, was nicht performant ist (muss noch optimiert werden).

Sind Sachen, die ich später vielleicht implementiere, aber jetzt gerade recht viel Aufwand sind

2024-12-10 09:05 UTC, bafto submitted a review, later dismissed

2024-12-10 14:14 UTC, bafto approved these changes

2024-12-10 14:15 UTC, merged