Windows Pfade, Arbeitsverzeichnis und Ist_Lateinischer_Buchstabe/-_Oder_Zahl Funktionen
DDP-Projekt/Kompilierer pull request #58
Opened 2024-04-24 20:14 UTC by NotLe0n

# Folgende Funktionen sind neu:
## Duden/Laufzeit
- Arbeitsverzeichnis

## Duden/Zeichen
- Ist_Lateinischer_Buchstabe
- Ist_Lateinischer_Buchstabe_Oder_Zahl

## Duden/Pfade
- Windows_Ist_Absolut
- Windows_Saeubern
- Windows_Pfad_Verbinden
- Windows_Laufwerkbuchstabe
- Windows_VollständigerPfad
- Windows_Ordnerpfad
- Windows_Basisname
- Windows_Datei_Name
- Windows_Erweiterung

Dazu wurden die bisherigen Funktionen umbennant, sodass es klar ist, dass sie nur für UNIX Pfade da sind.

2024-04-25 18:26 UTC, bafto commented on lib/stdlib/Duden/Laufzeit.ddp
> +	"den Arbeitsverzeichnis"
"der Arbeitsverzeichnis" -> "das Arbeitsverzeichnis"
"den Arbeitsverzeichnis" -> "dem Arbeitsverzeichnis"

2024-04-25 18:29 UTC, bafto commented on lib/stdlib/include/winapi-path.h
> +#include <string.h>
beide includes nicht in der Header Datei benötigt -> nur <stdbool.h> nötig

2024-04-25 18:30 UTC, bafto commented on lib/stdlib/include/winapi-path.h
> +#define MAX_PATH 260
Lieber "ddpwindows.h" includen und das MAX_PATH aus der WinApi verwenden

2024-04-25 18:32 UTC, bafto commented on lib/stdlib/source/path.c
> +#include <stdio.h>
<stdio.h> unused (zumindest auf Windows)

2024-04-25 18:33 UTC, bafto commented on lib/stdlib/source/path.c
> +		ret->str = DDP_ALLOCATE(char, 1);
Allocation ist unnötig. DDP_EMPTY_STRING ist ein valider leerer string, und kann so returned werden (also nicht direkt, aber durch `*ret = DDP_EMTPY_STRING; return;`

2024-04-25 18:36 UTC, bafto commented on lib/stdlib/source/path.c
> +		ret->str = DDP_ALLOCATE(char, 1);
Selbe unnötige Allocation wie oben

2024-04-25 18:37 UTC, bafto commented on lib/stdlib/source/runtime_util.c
> +#define MAX_PATH_LENGTH 4096 // windows is 260 (without reg edit), linux 4096
bitte `#ifdef` was zwischen Linux und Windows unterscheidet (und am bestem den WinApi MAX_PATH verwendet)

2024-04-25 18:39 UTC, bafto commented on lib/stdlib/source/runtime_util.c
> +		char *string = DDP_ALLOCATE(char, MAX_PATH_LENGTH + 1);
unnötig große Allocation. `strlen(buffer) + 1` sollte benutzt werden, da getcwd bereits einen nullterminierten string zurückgibt.

2024-04-25 18:40 UTC, bafto commented on lib/stdlib/source/runtime_util.c
> +	ret->cap = 0;
prefer `*ret = DDP_EMPTY_STRING;`

2024-04-25 18:42 UTC, bafto commented on tests/testdata/stdlib/Pfade/Pfade.ddp
Vielleicht noch Tests, die MAX_PATH überschreiten. Außerdem sollte bei solchen Fehlern (die ja abgefangen werden können) `Duden/Fehlerbehandlung` verwendet werden. Das kann man aber noch im Nachhinein einbauen.

2024-04-25 18:47 UTC, bafto commented on lib/stdlib/Duden/Pfade.ddp
Soweit ich sehe gibt es im Moment von jeder Funktion die UNIX und Windows Variante. Für die Funktionen, die es auf beiden Betriebssystemen gibt sollte es Wrapper-Funktionen geben, die die Korrekte Variante aufrufen. Sonst muss der Nutzer immer von Hand:
```
Wenn das Betriebssystem gleich "Windows" ist, dann:
    Gib den absoluten UNIX Pfad zu pfad zurück.
Sonst:
    Gib den absoluten Windows Pfad zu pfad zurück.
```
schreiben.

2024-04-25 18:52 UTC, bafto requested changes
Siehe Kommentare

2024-04-26 17:46 UTC, bafto approved these changes

2024-04-26 18:07 UTC, NotLe0n commented on tests/testdata/stdlib/Pfade/Pfade.ddp
Test hinzugefügt, Fehlerbehandlung wird in eigene issue verlegt (#62)

2024-04-26 19:01 UTC, merged